### PR TITLE
Added platform interrupt functions.

### PR DESCRIPTION
**Pull request by jpellikk-arm**
@kjbracey-arm Implementations for the interrupts enabled/disabled HAL functions.

### CODE REVIEW

**Comment by 0xc0170** [comment]
Would it make sense to use atomic incr/decrement?

**Comment by jpellikk-arm** [comment]
Possibly yes. Are you suggesting defining the counter as std::atomic/C++11 and using that?

I think making the counter atomic would make a different commit.

**Comment by 0xc0170** [comment]
> Possibly yes. Are you suggesting defining the counter as std::atomic/C++11 and using that?

I forgot to share this reference: https://github.com/ARMmbed/core-util/blob/master/core-util/atomic_ops.h

**Comment by kjbracey-arm** [comment]
I don't currently see any need for atomic ops here. All current code using this interrupt-type implementation of this API is fundamentally single-threaded in the foreground - all it has to worry about is interrupts, and interrupt routines will put the counter back before they exit.

The other possible implementation of this API is one where there is one application thread and one driver thread, and it becomes a blocking mutex. The API is then never called from interrupts. That implementation would need to worry about atomicity - but it would normally be taken care of by the system mutex call.

If we ever hit an implementation that uses both multiple threads and interrupts, we'd need to do more work to properly separate the two concepts in the code using platform_enter_critical. And at that point I rework the API to return "old_state" rather than having a counter.

**Comment by kjbracey-arm** [comment]
The name "interrupts_enabled" is wrong/misleading - for sanity, that call should be made before interrupts get re-enabled, but after you've finished calling platform_enter_critical users. The correct sequence is

   Interrupts are disabled (eg on IRQ entry)
   call platform_interrupts_disabled
   call functions using platform_enter_critical/platform_exit_critical
   call platform_interrupts_enabling (being_enabled?)
   Interrupts are enabled (eg on IRQ exit)

I so wish enter/exit had been properly defined in the first place so we didn't have to do this...

**Comment by jpellikk-arm** [comment]
Any suggestions for the better naming? I will just go for _enabling...

**Pull request merged**
