### PR TITLE
Adaptation to configuration-store.

### PR DESCRIPTION
**Pull request by artokin**
Note! nvm.h is not in final location, need to find home for it.

### CODE REVIEW

**Comment by artokin** [comment]
@kjbracey-arm would you please comment

**Comment by kjbracey-arm** [comment]
As discussed

I think the header file belongs in libservice/platform.

nvm_init() functionality isn't clear

Probably do want nvm_key_delete().

Not clear what happens if you write a shorter-than-max-len value then read it back - is current length stored?

Need to clarify what nvm_flush does.

Maybe want more of a prefix on the name - platform_nvm?

**Comment by artokin** [comment]
@terhei , @mikter would you please review?

**Comment by mikter** [comment]
+1

**Comment by artokin** [comment]
Old NVM code not needed anymore, close the PR.

**Pull request closed without merging**
